-- MySQL Script generated by MySQL Workbench
-- Sun May 30 02:14:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db20210530
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db20210530
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db20210530` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db20210530` ;

-- -----------------------------------------------------
-- Table `db20210530`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db20210530`.`usuarios` (
  `IDUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBREUSUARIO` VARCHAR(45) NOT NULL,
  `PASSUSUARIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db20210530`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db20210530`.`vehiculos` (
  `PLACA` VARCHAR(45) NOT NULL,
  `TIPO_SERVICIO` VARCHAR(45) NOT NULL,
  `ESTADO` VARCHAR(45) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `LINEA` VARCHAR(45) NOT NULL,
  `MODELO` VARCHAR(45) NOT NULL,
  `CILINDRAJE` VARCHAR(45) NOT NULL,
  `COLOR` VARCHAR(45) NOT NULL,
  `TECNICO` VARCHAR(45) NOT NULL,
  `SOAT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PLACA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db20210530`.`antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db20210530`.`antecedentes` (
  `IDANTECEDENTE` INT NOT NULL AUTO_INCREMENT,
  `DESCANTECENTE` VARCHAR(45) NOT NULL,
  `vehiculos_PLACA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDANTECEDENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db20210530`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db20210530`.`ingresos` (
  `IDINGRESO` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(45) NOT NULL,
  `FECHA` DATETIME NOT NULL,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  `vehiculos_PLACA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDINGRESO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
